[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['openzeppelin-contracts-06/math/=lib/openzeppelin-contracts/contracts/utils/math/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config